name: Release

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Update 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          npm update all-the-package-repos
          npm run build
          npm test
          [[ `git status --porcelain` ]] || exit 0
  
          git add .
          # bump the version, commit, and create a tag
          git commit -m "Update package names"
          git push
